-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 22:58:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema symbiot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema symbiot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `symbiot` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `symbiot` ;

-- -----------------------------------------------------
-- Table `symbiot`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `symbiot`.`account` (
  `Account_Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `ContactPerson` VARCHAR(100) NULL DEFAULT NULL,
  `Address` VARCHAR(500) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Phone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Account_Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `symbiot`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `symbiot`.`role` (
  `Role_Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Role` VARCHAR(45) NOT NULL,
  `Privilege` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Role_Id`),
  UNIQUE INDEX `id_UNIQUE` (`Role_Id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `symbiot`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `symbiot`.`user` (
  `User_Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL DEFAULT NULL,
  `Login` VARCHAR(100) NOT NULL,
  `Password` VARCHAR(500) NOT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Mobile` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`User_Id`),
  UNIQUE INDEX `id_UNIQUE` (`User_Id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `symbiot`.`user_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `symbiot`.`user_account` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `User_Id` INT(10) UNSIGNED NOT NULL,
  `Account_Id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `user_Acc_FK_idx` (`User_Id` ASC) VISIBLE,
  INDEX `account_Acc_FK_idx` (`Account_Id` ASC) VISIBLE,
  CONSTRAINT `account_Acc_FK`
    FOREIGN KEY (`Account_Id`)
    REFERENCES `symbiot`.`account` (`Account_Id`),
  CONSTRAINT `user_Acc_FK`
    FOREIGN KEY (`User_Id`)
    REFERENCES `symbiot`.`user` (`User_Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `symbiot`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `symbiot`.`user_role` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `User_Id` INT(10) UNSIGNED NOT NULL,
  `Role_Id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `user_idx` (`User_Id` ASC) VISIBLE,
  INDEX `roleFK_idx` (`Role_Id` ASC) VISIBLE,
  CONSTRAINT `roleFK`
    FOREIGN KEY (`Role_Id`)
    REFERENCES `symbiot`.`role` (`Role_Id`),
  CONSTRAINT `userFK`
    FOREIGN KEY (`User_Id`)
    REFERENCES `symbiot`.`user` (`User_Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


CREATE TABLE symbiot.device (
	device_id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	devicename varchar(100) NULL,
	devicetype varchar(100) NULL,
	mac varchar(100) NULL,
	adddate TIMESTAMP NULL,
	datastr varchar(100) NULL,
	laststatus INT NULL,
	PRIMARY KEY (`device_id`),
  UNIQUE INDEX `id_UNIQUE` (`device_id` ASC) VISIBLE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE symbiot.devicemapping (
	devicemapping_Id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	account_Id INT NOT NULL,
	user_Id INT NOT NULL,
	device_Id INT NOT NULL,
	mappingstatus INT NOT NULL,
	PRIMARY KEY (`devicemapping_Id`),
  UNIQUE INDEX `id_UNIQUE` (`devicemapping_Id` ASC) VISIBLE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;
